### PR TITLE
Automate Python release

### PR DESCRIPTION
**Pull request by davidgasquez**
Heya @michael-erasmus! I spent some time this afternoon trying to setup an easy workflow for this repository.

Once we merge this PR `buda` will be available (from version `0.4.4`) in Pypi! The Travis script is now uploading the code that gets merged into master and will fail if we don't update versions since `twine` won't be able to tag the new file in Pypi.

Let me know how does this looks and if you have any comments. 😄   

Closes https://github.com/bufferapp/buda-protobufs/issues/12 (I've created https://github.com/bufferapp/buda-protobufs/issues/17 for `npm`)

### CODE REVIEW

**Comment by michael-erasmus** [comment]
Hey @davidgasquez!

This is awesome, thanks for pulling this together! I had two questions:

1) Will we stop relying on Github releases? Curious what the best flow would be for 'beta' releases that we're still testing. So far I've been able to test those out by manually uploading a GH release that I can point to.
2) Not super important, but I was wondering if perhaps we should name the package something more distinguishing in Pypi? Since this package is very specific to us, maybe we could add a `buffer_` prefix or something (so like `buffer_buda`)

**Comment by davidgasquez** [comment]
Hey @michael-erasmus! These are good questions 😉 

> Will we stop relying on Github releases? Curious what the best flow would be for 'beta' releases that we're still testing. So far I've been able to test those out by manually uploading a GH release that I can point to.

I can see a few option for the `beta` releases:
1. [Add another deployment command to `.travis.yml` that uploads code in a certain branch to a specific Github release](https://docs.travis-ci.com/user/deployment/releases/) (_I'm not sure if this kind of deployment fails when a release is still in place_). With this in place, all the code pushed to a `dev` branch will upload a `beta` release to Github.
1. Upload `beta` releases also to Pypi passing an argument to the deployment script forwarding the current branch. Modifications in other branches will publish always with an extra `beta` tag (`0.4.4-beta`). 

I think I prefer the first option if it's possible to replace releases. I can see a huge amount of releases adding in if we upload to Pypi with each change to master! 🙈 Still not sure which one to choose and I'd love to hear your thoughts on this. 😄

 > Not super important, but I was wondering if perhaps we should name the package something more distinguishing in Pypi? Since this package is very specific to us, maybe we could add a buffer_ prefix or something (so like buffer_buda)

True! I'll make the necessary changes.

**Comment by davidgasquez** [comment]
Just pushed https://github.com/bufferapp/buda-protobufs/pull/18/commits/885629b6e093146a57aaa63ac63e36d0fe0887c8, `buda` is now `buffer_buda` in Pypi!

**Comment by michael-erasmus** [comment]
@davidgasquez 

> 1. Add another deployment command to .travis.yml that uploads code in a certain branch to a specific Github release (I'm not sure if this kind of deployment fails when a release is still in place). With this in place, all the code pushed to a dev branch will upload a beta release to Github.

> 2. Upload beta releases also to Pypi passing an argument to the deployment script forwarding the current branch. Modifications in other branches will publish always with an extra beta tag (0.4.4-beta).

Wow, didn't know Travis could do that! I would also prefer option 1 since it feels more proper to release to GH when it's still in development. 

> I think I prefer the first option if it's possible to replace releases. I can see a huge amount of releases adding in if we upload to Pypi with each change to master! :see_no_evil: Still not sure which one to choose and I'd love to hear your thoughts on this. :smile:

Yeah, I'm with you there! That is why I thought it could be cool if it was still a manual script, since we can then control when we want to upload a release to GH. But if we can replace Beta versions, that could be fine as well. 

I've been thinking that perhaps with having the `buda-dev` project that can pull all the repos into it's own directory, maybe we could also make it so that we can point to dev packages just using relative paths for now? 

I'm thinking your current PR is good enough though to start with, and it already solves the problem for deploying changes to production. So maybe we could go ahead and merge this and still work on the beta version workflow after?

**Comment by davidgasquez** [comment]
> I've been thinking that perhaps with having the buda-dev project that can pull all the repos into it's own directory, maybe we could also make it so that we can point to dev packages just using relative paths for now?

This sounds good! I think it'll give us a lot of flexibility and make things simpler for the moment!

> So maybe we could go ahead and merge this and still work on the beta version workflow after?

Just merged it and [it worked](https://travis-ci.org/bufferapp/buda-protobufs/builds/271605477)! 🎉 It'll publish all the changes to master. If we see that being an issue¹ we can publish only on releases/tags too. 

¹ Some changes might not impact the actual package (modifying the README file) but will require a change in the package version or it will fail when published.

**Comment by michael-erasmus** [comment]
Awesome stuff, thanks @davidgasquez!

**Comment by djfarrelly** [comment]
Hey @davidgasquez, I wonder if we could potentially catch the duplicate version error to still mark the build as successful? It was giving build failures on master which made me worried, but it was only a duplicate version published

https://travis-ci.org/bufferapp/buda-protobufs/builds/272628398?utm_source=email&utm_medium=notification

**Comment by davidgasquez** [comment]
Hey @djfarrelly! That's something I've been thinking on tweaking. I think we can probably catch the `File already exists` error but probably we want to switch the way we deploy, from using the `master` branch to [using `tags`](https://docs.travis-ci.com/user/deployment/pypi/#Deploying-tags). 

This might be much cleaner since we don't need to edit any code and we'll have better control over releases.😄 How does that change sounds? I can quickly send a PR if it feels good!

**Pull request merged**
